USE [master]
GO

/****** Object:  Database [Funnel]    Script Date: 07/14/2016 4:26:06 PM ******/
DROP DATABASE [Funnel]
GO

/****** Object:  Database [Funnel]    Script Date: 07/14/2016 4:26:06 PM ******/
CREATE DATABASE [Funnel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Funnel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Funnel.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Funnel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Funnel_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Funnel] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Funnel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Funnel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Funnel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Funnel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Funnel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Funnel] SET ARITHABORT OFF 
GO

ALTER DATABASE [Funnel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Funnel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Funnel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Funnel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Funnel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Funnel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Funnel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Funnel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Funnel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Funnel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Funnel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Funnel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Funnel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Funnel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Funnel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Funnel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Funnel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Funnel] SET RECOVERY FULL 
GO

ALTER DATABASE [Funnel] SET  MULTI_USER 
GO

ALTER DATABASE [Funnel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Funnel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Funnel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Funnel] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Funnel] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Funnel] SET  READ_WRITE 
GO


